version: "3.8"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    command: ['mysqld',
              '--character-set-server=utf8mb4',
              '--collation-server=utf8mb4_unicode_ci']
  app:
    build: .
    restart: on-failure
    depends_on:
      - mysql
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul

volumes:
  mysql: