spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:lo_gallery}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:myuser}
    password: ${MYSQL_PW:123456}

  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    hibernate.ddl-auto: create
    properties:
      hibernate.format_sql: true