name: Auto Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Git Pull on Deployment Server
      run: |
        ssh ubuntu@13.236.242.211 'cd gallery_backend && git pull'

    - name: Docker Compose Up
      run: |
        ssh ubuntu@13.236.242.211 'cd gallery_backend && docker-compose up -d'
